# -*- coding: utf-8 -*-
"""bahttransfer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10RpB3ScEqmfuDx6hqlqpKyBAl_-70fEV
"""

money = int(input("กรุณาใส่เงิน : "))
Am = money//500   #จำนวนแบงค์500
As = money%500  #เศษ500
Bm = As//100  #จำนวนแบงค์100
Bs = As%100   #เศษ100
Cm = Bs//50   #จำนวนแบงค์50
Cs = Bs%50  #เศษ50
Dm = Cs//20   #จำนวนแบงค์20
Ds = Cs%20  #เศษ20
Em = Ds//10   #จำนวนเหรียญ10
Es = Ds%10  #เศษ10
Fm = Es//5  #จำนวนเหรียญ5
Fs = Es%5   #เศษ5
Gm = Fs//2  #จำนวนเหรียญ2
Gs = Fs%2   #จำนวนเหรียญ1

print("ธนบัตรใบละ 500 บาทจำนวน %d ใบ" %Am)
print("ธนบัตรใบละ 100 บาทจำนวน %d ใบ" %Bm)
print("ธนบัตรใบละ 50 บาทจำนวน %d ใบ" %Cm)
print("ธนบัตรใบละ 20 บาทจำนวน %d ใบ" %Dm)
print("เหรียญ 10 บาทจำนวน %d เหรียญ" %Em)
print("เหรียญ 5 บาทจำนวน %d เหรียญ" %Fm)
print("เหรียญ 2 บาทจำนวน %d เหรียญ" %Gm)
print("เหรียญ 1 บาทจำนวน %d เหรียญ" %Gs)